import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Lang = "en" | "bn";

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // NAVBAR
    nav_flat_listing: "Flat Listing",
    nav_building_management: "Building Management",
    nav_property_management: "Property Management",
    nav_services: "Services",
    nav_pricing: "Pricing",
    nav_contact: "Contact Us",
    nav_login: "Login",
    nav_get_started: "Get Started",

    // HOMEPAGE HERO
    hero_headline_1: "Bangladesh's 1st Smart",
    hero_headline_2: "Digital Property Ecosystem",
    hero_sub: "Bangladesh's all-in-one platform for landlords, renters, and building managers. Find homes, collect rent, and manage buildings — digitally.",
    hero_btn_explore: "Explore Rentals",
    hero_btn_how: "See How It Works",
    hero_stat_1: "15,000+ Rental Listings",
    hero_stat_2: "500+ Buildings Managed",
    hero_stat_3: "4 Cities Covered",
    hero_trust: "Trusted by property owners across Dhaka, Chittagong, Rajshahi & Khulna",

    // FEATURE CARDS
    cards_section_title: "Everything You Need, In One Platform",
    cards_section_sub: "Built for landlords, renters, and building associations across Bangladesh",
    card1_tag: "Find A Home",
    card1_title: "Flat Listing",
    card1_desc: "Browse thousands of verified flats across Dhaka, Chittagong, Rajshahi & Khulna. No fake listings.",
    card1_stat1: "124+ Listings",
    card1_stat2: "Verified Only",
    card1_stat3: "4 Cities",
    card2_tag: "For Associations",
    card2_title: "Building Management",
    card2_desc: "Manage service charges, building funds, expenses and residents from one powerful dashboard.",
    card2_stat1: "Live Dashboard",
    card2_stat2: "Payment Tracking",
    card2_stat3: "Reports",
    card3_tag: "For Landlords",
    card3_title: "Property Management",
    card3_desc: "Track rent payments, manage tenants, send automated reminders and monitor your monthly income.",
    card3_stat1: "Auto Reminders",
    card3_stat2: "Rent Tracking",
    card3_stat3: "Statements",
    card4_tag: "On-Demand",
    card4_title: "Services",
    card4_desc: "Book verified plumbers, electricians, cleaners and repair experts at your doorstep.",
    card4_stat1: "8 Service Types",
    card4_stat2: "Verified Pros",
    card4_stat3: "Doorstep",
    card_explore: "Explore",

    // HOW IT WORKS
    how_title: "How Rento Works",
    how_step: "Step",
    how_step1_title: "Create Your Account",
    how_step1_desc: "Sign up as a landlord, renter, or building manager",
    how_step2_title: "List or Find Property",
    how_step2_desc: "Post your property or search from thousands of listings",
    how_step3_title: "Manage Everything Digitally",
    how_step3_desc: "Collect rent, track expenses, and manage tenants online",

    // ABOUT
    about_label: "About Rento",
    about_title: "Built for Bangladesh's Property Market",
    about_body: "Rento was founded by Muhammad Mushfiqur Rahman and Esrar Bin Haque with one mission — to bring Bangladesh's fragmented, offline property market into the digital age.",
    about_check1: "Verified listings across 4 major cities",
    about_check2: "Digital rent collection via bKash, Nagad & cards",
    about_check3: "Transparent building fund management",
    about_link: "Learn More About Us",

    // SERVICES DETAIL SECTION
    services_section_title: "Our Services, In Detail",
    service1_title: "Rental Marketplace",
    service1_body: "Search and discover verified rental properties with real photos, accurate pricing, and location maps.",
    service2_title: "Smart Building Management",
    service2_body: "Track service charge collections, building fund balances, resident contributions, and maintenance expenses.",
    service3_title: "Digital Rent Collection",
    service3_body: "Landlords can collect rent digitally via bKash, Nagad, debit/credit cards powered by SSLCommerz.",
    service4_title: "Home Services On-Demand",
    service4_body: "Book trusted local service providers for plumbing, electrical, cleaning, painting, and more.",
    services_verified_listings: "Verified Listings",
    services_location_filter: "Location Filter",
    services_direct_contact: "Direct Contact",
    services_pie_charts: "Pie Charts",
    services_expense_logs: "Expense Logs",
    services_fund_tracking: "Fund Tracking",
    services_bkash: "bKash",
    services_nagad: "Nagad",
    services_auto_records: "Auto Records",
    services_verified_workers: "Verified Workers",
    services_fast_booking: "Fast Booking",
    services_transparent_pricing: "Transparent Pricing",

    // PRICING
    pricing_title: "Simple, Transparent Pricing",
    pricing_sub: "Choose the plan that fits your needs. No hidden fees.",
    pricing_popular: "Most Popular",
    pricing_plan1_name: "Small Building",
    pricing_plan1_sub: "Perfect for single small buildings",
    pricing_plan2_name: "Medium Building",
    pricing_plan2_sub: "For growing property portfolios",
    pricing_plan3_name: "Large Building",
    pricing_plan3_sub: "For large complexes and associations",
    pricing_btn_trial: "Start Free Trial",
    pricing_btn_contact: "Contact Sales",
    pricing_note: "All plans include a 14-day free trial. No credit card required.",
    pricing_per_month: "/month",
    pricing_f1: "Up to 2 property listings",
    pricing_f2: "Basic tenant records",
    pricing_f3: "Manual payment tracking",
    pricing_f4: "Email support",
    pricing_f5: "Digital rent collection",
    pricing_f6: "Building management dashboard",
    pricing_f7: "Automated reminders",
    pricing_f8: "Up to 20 property listings",
    pricing_f9: "Full tenant management",
    pricing_f10: "Digital rent collection (SSLCommerz)",
    pricing_f11: "Automated payment reminders",
    pricing_f12: "Expense tracking",
    pricing_f13: "Priority support",
    pricing_f14: "Multi-building management",
    pricing_f15: "Unlimited property listings",
    pricing_f16: "Full building management dashboard",
    pricing_f17: "Service charge tracking",
    pricing_f18: "Building fund management",
    pricing_f19: "Pie charts & financial reports",
    pricing_f20: "Multi-building support",
    pricing_f21: "Dedicated account manager",
    pricing_f22: "Custom branding",

    // FOOTER
    footer_tagline: "Bangladesh's Digital Property Ecosystem",
    footer_links_title: "Quick Links",
    footer_contact_title: "Contact Us",
    footer_home: "Home",
    footer_rights: "All rights reserved",
    footer_privacy: "Privacy Policy",
    footer_terms: "Terms of Service",

    // CONTACT PAGE
    contact_title: "Get In Touch",
    contact_sub: "Have questions about Rento? We'd love to hear from you.",
    contact_name: "Full Name",
    contact_phone: "Phone Number",
    contact_email: "Email Address",
    contact_subject: "Subject",
    contact_message: "Message",
    contact_submit: "Send Message",
    contact_response: "We typically respond within 24 hours",
    contact_office_title: "Our Office",
    contact_office_detail: "House 12, Road 5, Dhanmondi, Dhaka-1209",
    contact_phone_title: "Call Us",
    contact_phone_hours: "Mon–Sat, 9AM–6PM",
    contact_email_title: "Email Us",
    contact_email_reply: "We reply within 24 hours",
    contact_social_title: "Follow Us",
    contact_map_label: "Rento HQ — Dhanmondi, Dhaka",
    contact_success: "Message sent! We'll get back to you soon.",

    // LOGIN / REGISTER
    login_welcome: "Welcome Back",
    login_sub: "Login to manage your properties",
    login_tab_owner: "Owner / Manager",
    login_tab_tenant: "Tenant",
    login_phone_label: "Phone Number",
    login_phone_placeholder: "01XXXXXXXXX",
    login_password_label: "Password",
    login_forgot: "Forgot Password?",
    login_btn: "Login",
    login_no_account: "Don't have an account?",
    login_register_link: "Register",
    login_invalid_phone: "Enter a valid 11-digit phone number starting with 01",
    login_password_required: "Password is required",
    register_title: "Create Account",
    register_sub: "Join Rento to manage your properties",
    register_name: "Full Name",
    register_role: "I am a",
    register_role_owner: "Property Owner",
    register_role_manager: "Building Manager",
    register_role_tenant: "Tenant",
    register_password: "Password",
    register_confirm: "Confirm Password",
    register_btn: "Create Account",
    register_have_account: "Already have an account?",
    register_login_link: "Login",
    register_name_required: "Name is required",
    register_password_min: "Password must be at least 6 characters",
    register_password_mismatch: "Passwords do not match",

    // FLAT LISTING PAGE
    flat_search_placeholder: "Search properties...",
    flat_filter_title: "Filter Results",
    flat_city_label: "City",
    flat_area_label: "Area",
    flat_all_areas: "All Areas",
    flat_price_label: "Price Range",
    flat_beds_label: "Bedrooms",
    flat_furnished_label: "Furnished",
    flat_available_label: "Available Now",
    flat_apply_btn: "Apply Filters",
    flat_reset_btn: "Reset",
    flat_found: "properties found in",
    flat_sort_label: "Sort by",
    flat_sort_newest: "Newest",
    flat_sort_low: "Price: Low to High",
    flat_sort_high: "Price: High to Low",
    flat_verified_badge: "Verified",
    flat_available_badge: "Available Now",
    flat_view_btn: "View Details",
    flat_per_month: "/ month",
    flat_beds: "Beds",
    flat_baths: "Baths",
    flat_property_type: "Property Type",
    flat_budget: "Budget",
    flat_previous: "Previous",
    flat_next: "Next",
    flat_yes: "Yes",
    flat_no: "No",
    flat_reviews: "reviews",

    // SERVICES PAGE
    services_search_placeholder: "What service do you need?",
    services_title: "Book Trusted Home Services",
    services_sub: "Verified professionals at your doorstep",
    services_categories: "Service Categories",
    services_featured: "Featured Providers",
    service_plumbing: "Plumbing",
    service_electrical: "Electrical",
    service_cleaning: "Cleaning",
    service_painting: "Painting",
    service_ac: "AC Repair",
    service_pest: "Pest Control",
    service_carpentry: "Carpentry",
    service_moving: "Moving Help",
    services_book_btn: "Book Now",
    services_from: "From",
    services_reviews: "reviews",

    // BUILDING MANAGEMENT DASHBOARD
    bm_dashboard_title: "Dashboard",
    bm_dashboard_sub: "Building management overview",
    bm_filter_month: "Filter by Month:",
    bm_card1_label: "Total Monthly Service Charge",
    bm_card1_sub: "This month's total",
    bm_card2_label: "Total Collected",
    bm_card2_sub: "collection rate",
    bm_card3_label: "Account Receivable",
    bm_card3_pending: "flats pending",
    bm_card3_overdue1: "month overdue",
    bm_card3_overdue2: "months overdue",
    bm_card3_flat: "flat",
    bm_card3_flats: "flats",
    bm_card4_label: "Total Expense",
    bm_card4_sub: "expense entries",
    bm_card5_label: "Account Payable",
    bm_card5_sub: "Association owes",
    bm_card6_label: "Cash In Hand",
    bm_card6_formula: "= Collected − Expense",
    bm_edit_btn: "Edit",
    bm_view_btn: "View",
    bm_save_btn: "Save",
    bm_cancel_btn: "Cancel",
    bm_edit_charge_title: "Edit Monthly Service Charge",
    bm_edit_charge_label: "Enter total monthly service charge",

    // CASH IN HAND PANEL
    cash_panel_title: "Cash In Hand Breakdown",
    cash_location_title: "Cash Location",
    cash_col_location: "Location",
    cash_col_amount: "Amount",
    cash_col_type: "Type",
    cash_col_updated: "Last Updated",
    cash_movement_title: "Cash Movement Log",
    cash_edit_btn: "Edit Locations",

    // ACCOUNT PAYABLE PANEL
    payable_panel_title: "Account Payable Details",
    payable_col_whom: "Whom",
    payable_col_type: "Type",
    payable_col_amount: "Amount",
    payable_col_date: "Date",
    payable_col_notes: "Notes",
    payable_mark_paid: "Mark Paid",
    payable_marked_toast: "Marked as paid",

    // OVERDUE SECTION
    overdue_title: "Overdue Payments",
    overdue_sub: "Residents who haven't paid for 1 or more months",
    overdue_col_name: "Resident Name",
    overdue_col_flat: "Flat",
    overdue_col_months: "Months Overdue",
    overdue_col_due: "Total Due",
    overdue_col_last: "Last Paid",
    overdue_col_action: "Action",
    overdue_send_reminder: "Send Reminder",
    overdue_reminder_toast: "Reminder sent to",
    overdue_month: "month",
    overdue_months: "months",

    // CHARTS
    chart_collection_title: "Service Charge Collection Trend",
    chart_collection_sub: "Monthly collected vs uncollected",
    chart_collected: "Collected",
    chart_not_collected: "Not Collected",
    chart_expense_title: "Expense Breakdown",
    chart_income_title: "Income vs Expense vs Account Payable",
    chart_income_sub: "Monthly financial health overview",
    chart_income: "Income",
    chart_expense: "Expense",
    chart_payable: "Account Payable",

    // RECENT PAYMENTS TABLE
    recent_title: "Recent Payments",
    recent_view_all: "View All",
    recent_col_name: "Resident Name",
    recent_col_flat: "Flat",
    recent_col_amount: "Amount",
    recent_col_method: "Method",
    recent_col_status: "Status",
    status_paid: "Paid",
    status_due: "Due",

    // SIDEBAR NAVIGATION (Building Management)
    sidebar_dashboard: "Dashboard",
    sidebar_buildings: "Buildings",
    sidebar_flats: "Flats",
    sidebar_flat_owner: "Flat Owner",
    sidebar_tenants: "Tenants",
    sidebar_payment_status: "Payment Status",
    sidebar_expenses: "Expenses",
    sidebar_account_payable: "Account Payable",
    sidebar_account_receivable: "Account Receivable",
    sidebar_reports: "Reports",
    sidebar_association: "Association",
    sidebar_settings: "Settings",
    sidebar_logout: "Log out",

    // BUILDINGS TAB
    buildings_title: "Building Information",
    buildings_edit_btn: "Edit Building Info",
    buildings_name: "Building Name",
    buildings_address: "Address",
    buildings_floors: "Total Floors",
    buildings_year: "Year Built",
    buildings_total_flats: "Total Flats",
    buildings_common: "Common Areas",
    buildings_occupied: "Occupied Flats",
    buildings_vacant: "Vacant Flats",
    buildings_fund_target: "Monthly Fund Target",
    buildings_fund_balance: "Building Fund Balance",
    buildings_flat_details: "Flat Details",
    buildings_add_flat: "+ Add Flat",
    buildings_col_flat: "Flat No.",
    buildings_col_floor: "Floor",
    buildings_col_size: "Size (sqft)",
    buildings_col_charge: "Service Charge",
    buildings_col_status: "Status",
    buildings_col_tenant: "Current Tenant",
    buildings_col_actions: "Actions",
    buildings_assign: "Assign",
    buildings_occupied_badge: "Occupied",
    buildings_vacant_badge: "Vacant",
    buildings_all_status: "All Status",

    // FLAT OWNER TAB
    flat_owner_title: "Flat Owners",
    flat_owner_add: "+ Add Owner",
    flat_owner_col_name: "Owner Name",
    flat_owner_col_phone: "Phone Number",
    flat_owner_col_nid: "NID Number",
    flat_owner_col_flat: "Flat No.",
    flat_owner_col_since: "Ownership Since",
    flat_owner_col_tenant: "Tenant Living",
    flat_owner_col_status: "Status",
    flat_owner_col_actions: "Actions",
    flat_owner_active: "Active",

    // TENANTS TAB
    tenants_title: "Tenants",
    tenants_add: "+ Add Tenant",
    tenants_col_name: "Name",
    tenants_col_phone: "Phone Number",
    tenants_col_nid: "NID Number",
    tenants_col_flat: "Flat No.",
    tenants_col_movein: "Move-in Date",
    tenants_col_charge: "Monthly Service Charge",
    tenants_col_status: "Status",
    tenants_col_actions: "Actions",
    tenants_active: "Active",
    tenants_view: "View",
    tenants_total_paid: "Total Paid This Year",
    tenants_advance: "Advance Held",
    tenants_payment_history: "Payment History",
    tenants_edit: "Edit Tenant",
    tenants_remove: "Remove Tenant",

    // PAYMENT STATUS TAB
    payment_title: "Payment Status",
    payment_add: "+ Record Payment",
    payment_total_col: "Total Collectable",
    payment_collected_col: "Total Collected",
    payment_due_col: "Total Due",
    payment_col_name: "Resident Name",
    payment_col_flat: "Flat",
    payment_col_charge: "Service Charge",
    payment_col_month: "Month",
    payment_col_date: "Payment Date",
    payment_col_method: "Method",
    payment_col_status: "Status",
    payment_col_action: "Action",
    payment_receipt: "Receipt",
    payment_remind: "Remind",

    // EXPENSES TAB
    expenses_title: "Expenses",
    expenses_add: "+ Add Expense",
    expenses_total: "Total Expenses This Month",
    expenses_covered: "Covered by Fund",
    expenses_borrowed: "Account Payable (Borrowed)",
    expenses_col_date: "Date",
    expenses_col_desc: "Description",
    expenses_col_amount: "Amount",
    expenses_col_category: "Category",
    expenses_col_paid_from: "Paid From",
    expenses_col_added_by: "Added By",
    expenses_fund: "Fund",
    expenses_borrowed_badge: "Borrowed",
    expenses_all_categories: "All Categories",
    expenses_total_label: "Total Expenses",

    // ACCOUNT PAYABLE TAB
    ap_title: "Account Payable",
    ap_sub: "Amounts the building association borrowed from the fund for expenses",
    ap_outstanding: "Total Outstanding Payable",
    ap_add: "+ Add Payable",
    ap_col_desc: "Expense Description",
    ap_col_date: "Date",
    ap_col_amount: "Amount Borrowed",
    ap_col_pay_to: "Pay To",
    ap_col_status: "Status",
    ap_col_action: "Action",
    ap_unpaid: "Unpaid",
    ap_paid: "Paid",
    ap_pending: "Pending",
    ap_mark_paid: "Mark Paid",
    ap_done: "Done",
    ap_total_payable: "Total Payable",

    // ACCOUNT RECEIVABLE TAB
    ar_title: "Account Receivable",
    ar_sub: "Service charges yet to be collected from residents",
    ar_outstanding: "Total Outstanding Receivable",
    ar_add: "+ Add Entry",
    ar_collect_from: "Collect from",
    ar_residents: "residents",
    ar_col_name: "Resident Name",
    ar_col_flat: "Flat",
    ar_col_type: "Type",
    ar_col_amount: "Amount Due",
    ar_col_due_date: "Due Date",
    ar_col_days: "Days Overdue",
    ar_col_action: "Action",
    ar_col_status: "Status",
    ar_send_reminder: "Send Reminder",
    ar_remind: "Remind",
    ar_overdue: "Overdue",
    ar_upcoming: "Upcoming",
    ar_total_receivable: "Total Receivable",

    // REPORTS TAB
    reports_title: "Reports",
    reports_sub: "Financial summary and insights",
    reports_generate: "Generate Invoice",
    reports_download: "Download PDF",
    reports_print: "Print Invoice",
    reports_close: "Close",
    reports_monthly_title: "Monthly Invoice",
    reports_monthly_desc: "Generate individual service charge invoice for a specific flat/tenant",
    reports_full_title: "Full Monthly Report Invoice",
    reports_full_desc: "Generate a complete financial invoice for the entire association",
    reports_select_tenant: "Select Tenant",
    reports_select_month: "Select Month",
    reports_select_year: "Year",
    reports_generate_btn: "Generate Invoice",
    reports_generate_full_btn: "Generate Full Invoice",
    reports_generate_invoices: "Generate Invoices",
    reports_monthly_collection: "Monthly Collection Report",
    reports_monthly_collection_desc: "Service charge collection summary by month",
    reports_expense_report: "Expense Report",
    reports_expense_report_desc: "Detailed breakdown of all expenses by category",
    reports_outstanding_dues: "Outstanding Dues Report",
    reports_outstanding_dues_desc: "List of all pending payments and overdue amounts",
    reports_income_vs_expense: "Income vs Expense Report",
    reports_income_vs_expense_desc: "Profit/loss overview for each building",
    reports_generate_arrow: "Generate →",
    reports_pdf_coming: "PDF download coming soon",

    // ASSOCIATION TAB
    assoc_title: "Association",
    assoc_info_title: "Association Information",
    assoc_edit_btn: "Edit Association Info",
    assoc_name: "Association Name",
    assoc_established: "Established",
    assoc_total_members: "Total Members",
    assoc_admin: "Admin",
    assoc_roles_title: "Roles & Permissions",
    assoc_add_role: "+ Add Role",
    assoc_col_role: "Role Name",
    assoc_col_permissions: "Permissions",
    assoc_col_members: "Members Count",
    assoc_col_actions: "Actions",
    assoc_edit_role: "Edit",
    assoc_delete_role: "Delete",
    assoc_members_title: "Association Members",
    assoc_add_member: "+ Add Member",
    assoc_col_name: "Name",
    assoc_col_phone: "Phone",
    assoc_col_nid: "NID",
    assoc_col_joining: "Joining Date",
    assoc_col_status: "Status",
    assoc_remove: "Remove",
    assoc_note: "Only the Admin can add or remove members and manage roles.",
    assoc_save_role: "Save Role",
    assoc_add_member_btn: "Add Member",
    assoc_update_member_btn: "Update Member",
    assoc_confirm_remove: "Remove from association?",
    assoc_confirm_btn: "Confirm",
    assoc_cancel_btn: "Cancel",
    assoc_member_added: "Member added",
    assoc_member_removed: "removed",
    assoc_full_name: "Full Name",
    assoc_phone_number: "Phone Number",
    assoc_nid_number: "NID Number",
    assoc_role: "Role",
    assoc_joining_date: "Joining Date",

    // SETTINGS TAB
    settings_title: "Settings",
    settings_building_title: "Building Association Profile",
    settings_assoc_name: "Association name",
    settings_address: "Address",
    settings_floors: "Total floors",
    settings_total_flats: "Total flats",
    settings_fund_target: "Monthly fund target per flat",
    settings_save: "Save Changes",
    settings_notif_title: "Notification Preferences",
    settings_notif_1: "Send service charge reminders (3 days before due)",
    settings_notif_2: "Send overdue alerts to residents",
    settings_notif_3: "Send payment confirmation receipts",
    settings_notif_4: "Email notifications",
    settings_notif_5: "SMS notifications",
    settings_account_title: "Account",
    settings_manager_name: "Manager name",
    settings_phone: "Phone",
    settings_current_pass: "Current Password",
    settings_new_pass: "New Password",
    settings_confirm_pass: "Confirm Password",
    settings_update: "Update Profile",

    // PROPERTY MANAGEMENT SIDEBAR
    pm_sidebar_dashboard: "Dashboard",
    pm_sidebar_properties: "My Properties",
    pm_sidebar_units: "Units",
    pm_sidebar_tenants: "Tenants",
    pm_sidebar_rent: "Rent Payments",
    pm_sidebar_advance: "Advance Money Records",
    pm_sidebar_expenses: "Expenses",
    pm_sidebar_payable: "Account Payable",
    pm_sidebar_receivable: "Account Receivable",
    pm_sidebar_settings: "Settings",
    pm_property_management: "Property Management",
    pm_overview: "Overview of your properties",
    pm_my_properties: "My Properties",
    pm_monthly_income: "Monthly Income",
    pm_active_tenants: "Active Tenants",
    pm_pending_dues: "Pending Dues",
    pm_across4: "Across 4 locations",
    pm_all_active: "All active",
    pm_action_needed: "Action needed",
    pm_income_trend: "Income Collection Trend",
    pm_manage_rentals: "Manage your rental properties",
    pm_add_property: "Add Property",
    pm_property_name: "Property Name",
    pm_total_units: "Total Units",
    pm_add_unit: "Add Unit",
    pm_all_units: "All units across your buildings",
    pm_all_tenants: "All your tenants",
    pm_all_rent_history: "All rent payment history",
    pm_record_payment: "Record Payment",
    pm_track_transactions: "Track all rent transactions",
    pm_total_collectable: "Total Collectable",
    pm_rent_amount: "Rent Amount",
    pm_month: "Month",
    pm_payment_date: "Payment Date",
    pm_advance_money: "Advance Money Records",
    pm_advance_desc: "Track advance payments from tenants",
    pm_add_advance: "Add Record",
    pm_advance_amount: "Advance Amount",
    pm_date_received: "Date Received",
    pm_adjustment_status: "Adjustment Status",
    pm_notes: "Notes",
    pm_track_expenses: "Track building expenses",
    pm_add_expense: "Add Expense",
    pm_property_profile: "Property Profile",
    pm_this_month: "This month",
    pm_unit: "Unit",
    pm_property: "Property",
    pm_add_tenant: "Add Tenant",
    pm_reminders: "Reminders",
    pm_reminders_desc: "Reminders & Notifications",
    pm_pending_reminders: "Pending Reminders",
    pm_days_overdue: "days overdue",
    pm_send_reminder: "Send Reminder",
    pm_sent_log: "Sent Reminders Log",
    pm_date_sent: "Date Sent",
    pm_type: "Type",
    pm_message: "Message",
    pm_settings_desc: "Manage your dashboard settings",

    // GENERAL UI
    ui_search: "Search",
    ui_filter: "Filter",
    ui_view: "View",
    ui_edit: "Edit",
    ui_delete: "Delete",
    ui_save: "Save",
    ui_cancel: "Cancel",
    ui_close: "Close",
    ui_confirm: "Confirm",
    ui_loading: "Loading...",
    ui_no_data: "No data available for this month yet.",
    ui_coming_soon: "This section is coming soon.",
    ui_days_overdue: "days overdue",
    ui_all_buildings: "All Buildings",
    ui_all_status: "All Status",
    ui_occupied: "Occupied",
    ui_vacant: "Vacant",
    ui_paid: "Paid",
    ui_due: "Due",
    ui_active: "Active",
    ui_collected: "Collected",
    ui_pending: "Pending",
    ui_total: "Total",
    ui_actions: "Actions",
    ui_name: "Name",
    ui_phone: "Phone",
    ui_flat: "Flat",
    ui_tenant: "Tenant",
    ui_amount: "Amount",
    ui_method: "Method",
    ui_status: "Status",
    ui_date: "Date",
    ui_description: "Description",
    ui_category: "Category",
    ui_building: "Building",
    ui_size: "Size",
    ui_rent: "Rent",

    // Auth dashboard
    auth_dashboard: "Dashboard",
    auth_my_profile: "My Profile",
    auth_service_charge_updated: "Service charge updated",
  },
  bn: {
    // NAVBAR
    nav_flat_listing: "ফ্ল্যাট তালিকা",
    nav_building_management: "বিল্ডিং ম্যানেজমেন্ট",
    nav_property_management: "প্রপার্টি ম্যানেজমেন্ট",
    nav_services: "সেবাসমূহ",
    nav_pricing: "মূল্য পরিকল্পনা",
    nav_contact: "যোগাযোগ করুন",
    nav_login: "লগইন",
    nav_get_started: "শুরু করুন",

    // HOMEPAGE HERO
    hero_headline_1: "বাংলাদেশের ১ম স্মার্ট",
    hero_headline_2: "ডিজিটাল প্রপার্টি ইকোসিস্টেম",
    hero_sub: "বাড়িওয়ালা, ভাড়াটে এবং বিল্ডিং ম্যানেজারদের জন্য বাংলাদেশের সর্বোচ্চ ডিজিটাল প্ল্যাটফর্ম।",
    hero_btn_explore: "ভাড়া দেখুন",
    hero_btn_how: "কীভাবে কাজ করে",
    hero_stat_1: "১৫,০০০+ ভাড়ার তালিকা",
    hero_stat_2: "৫০০+ বিল্ডিং পরিচালিত",
    hero_stat_3: "৪টি শহরে সেবা",
    hero_trust: "ঢাকা, চট্টগ্রাম, রাজশাহী ও খুলনার সম্পত্তি মালিকদের আস্থার প্ল্যাটফর্ম",

    // FEATURE CARDS
    cards_section_title: "একটি প্ল্যাটফর্মে সব কিছু",
    cards_section_sub: "বাড়িওয়ালা, ভাড়াটে এবং বিল্ডিং অ্যাসোসিয়েশনের জন্য তৈরি",
    card1_tag: "বাড়ি খুঁজুন",
    card1_title: "ফ্ল্যাট তালিকা",
    card1_desc: "ঢাকা, চট্টগ্রাম, রাজশাহী ও খুলনায় হাজারো যাচাইকৃত ফ্ল্যাট ব্রাউজ করুন।",
    card1_stat1: "১২৪+ তালিকা",
    card1_stat2: "যাচাইকৃত",
    card1_stat3: "৪টি শহর",
    card2_tag: "অ্যাসোসিয়েশনের জন্য",
    card2_title: "বিল্ডিং ম্যানেজমেন্ট",
    card2_desc: "একটি শক্তিশালী ড্যাশবোর্ড থেকে সার্ভিস চার্জ, বিল্ডিং ফান্ড ও বাসিন্দা পরিচালনা করুন।",
    card2_stat1: "লাইভ ড্যাশবোর্ড",
    card2_stat2: "পেমেন্ট ট্র্যাকিং",
    card2_stat3: "রিপোর্ট",
    card3_tag: "বাড়িওয়ালার জন্য",
    card3_title: "প্রপার্টি ম্যানেজমেন্ট",
    card3_desc: "ভাড়া পেমেন্ট ট্র্যাক করুন, ভাড়াটে পরিচালনা করুন এবং মাসিক আয় পর্যবেক্ষণ করুন।",
    card3_stat1: "স্বয়ংক্রিয় রিমাইন্ডার",
    card3_stat2: "ভাড়া ট্র্যাকিং",
    card3_stat3: "স্টেটমেন্ট",
    card4_tag: "অন-ডিমান্ড",
    card4_title: "সেবাসমূহ",
    card4_desc: "যাচাইকৃত প্লাম্বার, ইলেকট্রিশিয়ান, ক্লিনার এবং মেরামত বিশেষজ্ঞ বুক করুন।",
    card4_stat1: "৮ ধরনের সেবা",
    card4_stat2: "যাচাইকৃত পেশাদার",
    card4_stat3: "দরজায় সেবা",
    card_explore: "দেখুন",

    // HOW IT WORKS
    how_title: "রেন্টো কীভাবে কাজ করে",
    how_step: "ধাপ",
    how_step1_title: "আপনার অ্যাকাউন্ট তৈরি করুন",
    how_step1_desc: "বাড়িওয়ালা, ভাড়াটে বা বিল্ডিং ম্যানেজার হিসেবে সাইন আপ করুন",
    how_step2_title: "সম্পত্তি তালিকাভুক্ত বা খুঁজুন",
    how_step2_desc: "আপনার সম্পত্তি পোস্ট করুন বা হাজারো তালিকা থেকে খুঁজুন",
    how_step3_title: "সবকিছু ডিজিটালি পরিচালনা করুন",
    how_step3_desc: "অনলাইনে ভাড়া সংগ্রহ করুন, খরচ ট্র্যাক করুন এবং ভাড়াটে পরিচালনা করুন",

    // ABOUT
    about_label: "রেন্টো সম্পর্কে",
    about_title: "বাংলাদেশের প্রপার্টি মার্কেটের জন্য তৈরি",
    about_body: "রেন্টো একটি লক্ষ্য নিয়ে প্রতিষ্ঠিত হয়েছে — বাংলাদেশের বিচ্ছিন্ন, অফলাইন প্রপার্টি মার্কেটকে ডিজিটাল যুগে নিয়ে আসা।",
    about_check1: "৪টি প্রধান শহরে যাচাইকৃত তালিকা",
    about_check2: "বিকাশ, নগদ ও কার্ডের মাধ্যমে ডিজিটাল ভাড়া সংগ্রহ",
    about_check3: "স্বচ্ছ বিল্ডিং ফান্ড ম্যানেজমেন্ট",
    about_link: "আমাদের সম্পর্কে আরও জানুন",

    // SERVICES DETAIL
    services_section_title: "আমাদের সেবাসমূহ বিস্তারিত",
    service1_title: "ভাড়ার বাজার",
    service1_body: "বাস্তব ছবি, সঠিক মূল্য এবং লোকেশন ম্যাপসহ যাচাইকৃত ভাড়ার সম্পত্তি খুঁজুন।",
    service2_title: "স্মার্ট বিল্ডিং ম্যানেজমেন্ট",
    service2_body: "সার্ভিস চার্জ সংগ্রহ, বিল্ডিং ফান্ড ব্যালেন্স এবং রক্ষণাবেক্ষণ খরচ ট্র্যাক করুন।",
    service3_title: "ডিজিটাল ভাড়া সংগ্রহ",
    service3_body: "SSLCommerz দ্বারা চালিত বিকাশ, নগদ, ডেবিট/ক্রেডিট কার্ডের মাধ্যমে ডিজিটালি ভাড়া সংগ্রহ করুন।",
    service4_title: "অন-ডিমান্ড হোম সার্ভিস",
    service4_body: "প্লাম্বিং, ইলেকট্রিক্যাল, পরিষ্কার, রং এবং আরও অনেক কিছুর জন্য বিশ্বস্ত স্থানীয় সেবা প্রদানকারী বুক করুন।",
    services_verified_listings: "যাচাইকৃত তালিকা",
    services_location_filter: "লোকেশন ফিল্টার",
    services_direct_contact: "সরাসরি যোগাযোগ",
    services_pie_charts: "পাই চার্ট",
    services_expense_logs: "খরচের লগ",
    services_fund_tracking: "ফান্ড ট্র্যাকিং",
    services_bkash: "বিকাশ",
    services_nagad: "নগদ",
    services_auto_records: "অটো রেকর্ড",
    services_verified_workers: "যাচাইকৃত কর্মী",
    services_fast_booking: "দ্রুত বুকিং",
    services_transparent_pricing: "স্বচ্ছ মূল্য",

    // PRICING
    pricing_title: "সহজ ও স্বচ্ছ মূল্য পরিকল্পনা",
    pricing_sub: "আপনার প্রয়োজন অনুযায়ী পরিকল্পনা বেছে নিন। কোনো লুকানো ফি নেই।",
    pricing_popular: "সবচেয়ে জনপ্রিয়",
    pricing_plan1_name: "ছোট বিল্ডিং",
    pricing_plan1_sub: "একটি ছোট বিল্ডিংয়ের জন্য আদর্শ",
    pricing_plan2_name: "মাঝারি বিল্ডিং",
    pricing_plan2_sub: "ক্রমবর্ধমান প্রপার্টি পোর্টফোলিওর জন্য",
    pricing_plan3_name: "বড় বিল্ডিং",
    pricing_plan3_sub: "বড় কমপ্লেক্স এবং অ্যাসোসিয়েশনের জন্য",
    pricing_btn_trial: "ফ্রি ট্রায়াল শুরু করুন",
    pricing_btn_contact: "বিক্রয় যোগাযোগ",
    pricing_note: "সব পরিকল্পনায় ১৪ দিনের বিনামূল্যে ট্রায়াল। কোনো ক্রেডিট কার্ড প্রয়োজন নেই।",
    pricing_per_month: "/মাস",
    pricing_f1: "সর্বোচ্চ ২টি সম্পত্তি তালিকা",
    pricing_f2: "বেসিক ভাড়াটে রেকর্ড",
    pricing_f3: "ম্যানুয়াল পেমেন্ট ট্র্যাকিং",
    pricing_f4: "ইমেইল সাপোর্ট",
    pricing_f5: "ডিজিটাল ভাড়া সংগ্রহ",
    pricing_f6: "বিল্ডিং ম্যানেজমেন্ট ড্যাশবোর্ড",
    pricing_f7: "অটোমেটেড রিমাইন্ডার",
    pricing_f8: "সর্বোচ্চ ২০টি সম্পত্তি তালিকা",
    pricing_f9: "সম্পূর্ণ ভাড়াটে ম্যানেজমেন্ট",
    pricing_f10: "ডিজিটাল ভাড়া সংগ্রহ (SSLCommerz)",
    pricing_f11: "অটোমেটেড পেমেন্ট রিমাইন্ডার",
    pricing_f12: "খরচ ট্র্যাকিং",
    pricing_f13: "প্রায়োরিটি সাপোর্ট",
    pricing_f14: "মাল্টি-বিল্ডিং ম্যানেজমেন্ট",
    pricing_f15: "আনলিমিটেড সম্পত্তি তালিকা",
    pricing_f16: "সম্পূর্ণ বিল্ডিং ম্যানেজমেন্ট ড্যাশবোর্ড",
    pricing_f17: "সার্ভিস চার্জ ট্র্যাকিং",
    pricing_f18: "বিল্ডিং ফান্ড ম্যানেজমেন্ট",
    pricing_f19: "পাই চার্ট ও আর্থিক রিপোর্ট",
    pricing_f20: "মাল্টি-বিল্ডিং সাপোর্ট",
    pricing_f21: "ডেডিকেটেড অ্যাকাউন্ট ম্যানেজার",
    pricing_f22: "কাস্টম ব্র্যান্ডিং",

    // FOOTER
    footer_tagline: "বাংলাদেশের ডিজিটাল প্রপার্টি ইকোসিস্টেম",
    footer_links_title: "দ্রুত লিঙ্ক",
    footer_contact_title: "যোগাযোগ করুন",
    footer_home: "হোম",
    footer_rights: "সর্বস্বত্ব সংরক্ষিত",
    footer_privacy: "গোপনীয়তা নীতি",
    footer_terms: "সেবার শর্তাবলী",

    // CONTACT PAGE
    contact_title: "যোগাযোগ করুন",
    contact_sub: "রেন্টো সম্পর্কে প্রশ্ন আছে? আমরা আপনার কথা শুনতে চাই।",
    contact_name: "পূর্ণ নাম",
    contact_phone: "ফোন নম্বর",
    contact_email: "ইমেইল ঠিকানা",
    contact_subject: "বিষয়",
    contact_message: "বার্তা",
    contact_submit: "বার্তা পাঠান",
    contact_response: "আমরা সাধারণত ২৪ ঘন্টার মধ্যে উত্তর দিই",
    contact_office_title: "আমাদের অফিস",
    contact_office_detail: "বাড়ি ১২, রোড ৫, ধানমন্ডি, ঢাকা-১২০৯",
    contact_phone_title: "কল করুন",
    contact_phone_hours: "সোম–শনি, সকাল ৯টা–সন্ধ্যা ৬টা",
    contact_email_title: "ইমেইল করুন",
    contact_email_reply: "আমরা ২৪ ঘন্টার মধ্যে উত্তর দিই",
    contact_social_title: "আমাদের অনুসরণ করুন",
    contact_map_label: "রেন্টো সদর দফতর — ধানমন্ডি, ঢাকা",
    contact_success: "বার্তা পাঠানো হয়েছে! আমরা শীঘ্রই যোগাযোগ করব।",

    // LOGIN / REGISTER
    login_welcome: "স্বাগতম",
    login_sub: "আপনার সম্পত্তি পরিচালনা করতে লগইন করুন",
    login_tab_owner: "মালিক / ম্যানেজার",
    login_tab_tenant: "ভাড়াটে",
    login_phone_label: "ফোন নম্বর",
    login_phone_placeholder: "০১XXXXXXXXX",
    login_password_label: "পাসওয়ার্ড",
    login_forgot: "পাসওয়ার্ড ভুলে গেছেন?",
    login_btn: "লগইন",
    login_no_account: "অ্যাকাউন্ট নেই?",
    login_register_link: "নিবন্ধন করুন",
    login_invalid_phone: "01 দিয়ে শুরু হওয়া ১১ সংখ্যার ফোন নম্বর দিন",
    login_password_required: "পাসওয়ার্ড প্রয়োজন",
    register_title: "অ্যাকাউন্ট তৈরি করুন",
    register_sub: "আপনার সম্পত্তি পরিচালনা করতে রেন্টোতে যোগ দিন",
    register_name: "পূর্ণ নাম",
    register_role: "আমি একজন",
    register_role_owner: "সম্পত্তি মালিক",
    register_role_manager: "বিল্ডিং ম্যানেজার",
    register_role_tenant: "ভাড়াটে",
    register_password: "পাসওয়ার্ড",
    register_confirm: "পাসওয়ার্ড নিশ্চিত করুন",
    register_btn: "অ্যাকাউন্ট তৈরি করুন",
    register_have_account: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    register_login_link: "লগইন",
    register_name_required: "নাম প্রয়োজন",
    register_password_min: "পাসওয়ার্ড কমপক্ষে ৬ অক্ষর হতে হবে",
    register_password_mismatch: "পাসওয়ার্ড মিলছে না",

    // FLAT LISTING PAGE
    flat_search_placeholder: "সম্পত্তি খুঁজুন...",
    flat_filter_title: "ফিল্টার করুন",
    flat_city_label: "শহর",
    flat_area_label: "এলাকা",
    flat_all_areas: "সকল এলাকা",
    flat_price_label: "মূল্য পরিসীমা",
    flat_beds_label: "বেডরুম",
    flat_furnished_label: "আসবাবসহ",
    flat_available_label: "এখনই পাওয়া যাচ্ছে",
    flat_apply_btn: "ফিল্টার প্রয়োগ করুন",
    flat_reset_btn: "রিসেট",
    flat_found: "টি সম্পত্তি পাওয়া গেছে",
    flat_sort_label: "সাজান",
    flat_sort_newest: "সর্বশেষ",
    flat_sort_low: "মূল্য: কম থেকে বেশি",
    flat_sort_high: "মূল্য: বেশি থেকে কম",
    flat_verified_badge: "যাচাইকৃত",
    flat_available_badge: "পাওয়া যাচ্ছে",
    flat_view_btn: "বিস্তারিত দেখুন",
    flat_per_month: "/ মাস",
    flat_beds: "বেড",
    flat_baths: "বাথ",
    flat_property_type: "সম্পত্তির ধরন",
    flat_budget: "বাজেট",
    flat_previous: "আগের",
    flat_next: "পরের",
    flat_yes: "হ্যাঁ",
    flat_no: "না",
    flat_reviews: "রিভিউ",

    // SERVICES PAGE
    services_search_placeholder: "কোন সেবা দরকার?",
    services_title: "বিশ্বস্ত হোম সার্ভিস বুক করুন",
    services_sub: "যাচাইকৃত পেশাদার আপনার দরজায়",
    services_categories: "সেবার ক্যাটাগরি",
    services_featured: "বৈশিষ্ট্যযুক্ত প্রোভাইডার",
    service_plumbing: "প্লাম্বিং",
    service_electrical: "ইলেকট্রিক্যাল",
    service_cleaning: "পরিষ্কার",
    service_painting: "রং করা",
    service_ac: "এসি মেরামত",
    service_pest: "কীটনাশক",
    service_carpentry: "কাঠমিস্ত্রি",
    service_moving: "মালামাল স্থানান্তর",
    services_book_btn: "এখনই বুক করুন",
    services_from: "শুরু",
    services_reviews: "রিভিউ",

    // BUILDING MANAGEMENT DASHBOARD
    bm_dashboard_title: "ড্যাশবোর্ড",
    bm_dashboard_sub: "বিল্ডিং ম্যানেজমেন্ট সংক্ষিপ্ত বিবরণ",
    bm_filter_month: "মাস অনুযায়ী ফিল্টার:",
    bm_card1_label: "মোট মাসিক সার্ভিস চার্জ",
    bm_card1_sub: "এই মাসের মোট",
    bm_card2_label: "মোট সংগৃহীত",
    bm_card2_sub: "সংগ্রহের হার",
    bm_card3_label: "প্রাপ্য হিসাব",
    bm_card3_pending: "টি ফ্ল্যাট বাকি",
    bm_card3_overdue1: "মাস বকেয়া",
    bm_card3_overdue2: "মাস+ বকেয়া",
    bm_card3_flat: "টি ফ্ল্যাট",
    bm_card3_flats: "টি ফ্ল্যাট",
    bm_card4_label: "মোট খরচ",
    bm_card4_sub: "টি খরচের এন্ট্রি",
    bm_card5_label: "পরিশোধযোগ্য হিসাব",
    bm_card5_sub: "অ্যাসোসিয়েশনের দেনা",
    bm_card6_label: "হাতে নগদ",
    bm_card6_formula: "= সংগৃহীত − খরচ",
    bm_edit_btn: "সম্পাদনা",
    bm_view_btn: "দেখুন",
    bm_save_btn: "সংরক্ষণ",
    bm_cancel_btn: "বাতিল",
    bm_edit_charge_title: "মাসিক সার্ভিস চার্জ সম্পাদনা",
    bm_edit_charge_label: "মোট মাসিক সার্ভিস চার্জ লিখুন",

    // CASH IN HAND PANEL
    cash_panel_title: "হাতে নগদ বিবরণ",
    cash_location_title: "নগদের অবস্থান",
    cash_col_location: "অবস্থান",
    cash_col_amount: "পরিমাণ",
    cash_col_type: "ধরন",
    cash_col_updated: "সর্বশেষ আপডেট",
    cash_movement_title: "নগদ লেনদেনের লগ",
    cash_edit_btn: "অবস্থান সম্পাদনা",

    // ACCOUNT PAYABLE PANEL
    payable_panel_title: "পরিশোধযোগ্য হিসাবের বিবরণ",
    payable_col_whom: "কাকে",
    payable_col_type: "ধরন",
    payable_col_amount: "পরিমাণ",
    payable_col_date: "তারিখ",
    payable_col_notes: "নোট",
    payable_mark_paid: "পরিশোধ হিসেবে চিহ্নিত",
    payable_marked_toast: "পরিশোধ হিসেবে চিহ্নিত করা হয়েছে",

    // OVERDUE SECTION
    overdue_title: "বকেয়া পেমেন্ট",
    overdue_sub: "যে বাসিন্দারা ১ বা তার বেশি মাস পেমেন্ট করেননি",
    overdue_col_name: "বাসিন্দার নাম",
    overdue_col_flat: "ফ্ল্যাট",
    overdue_col_months: "বকেয়া মাস",
    overdue_col_due: "মোট বকেয়া",
    overdue_col_last: "সর্বশেষ পেমেন্ট",
    overdue_col_action: "পদক্ষেপ",
    overdue_send_reminder: "রিমাইন্ডার পাঠান",
    overdue_reminder_toast: "রিমাইন্ডার পাঠানো হয়েছে",
    overdue_month: "মাস",
    overdue_months: "মাস",

    // CHARTS
    chart_collection_title: "সার্ভিস চার্জ সংগ্রহের ট্রেন্ড",
    chart_collection_sub: "মাসিক সংগৃহীত বনাম অসংগৃহীত",
    chart_collected: "সংগৃহীত",
    chart_not_collected: "অসংগৃহীত",
    chart_expense_title: "খরচের বিবরণ",
    chart_income_title: "আয় বনাম খরচ বনাম পরিশোধযোগ্য",
    chart_income_sub: "মাসিক আর্থিক স্বাস্থ্য সংক্ষিপ্ত বিবরণ",
    chart_income: "আয়",
    chart_expense: "খরচ",
    chart_payable: "পরিশোধযোগ্য",

    // RECENT PAYMENTS TABLE
    recent_title: "সাম্প্রতিক পেমেন্ট",
    recent_view_all: "সব দেখুন",
    recent_col_name: "বাসিন্দার নাম",
    recent_col_flat: "ফ্ল্যাট",
    recent_col_amount: "পরিমাণ",
    recent_col_method: "পদ্ধতি",
    recent_col_status: "অবস্থা",
    status_paid: "পরিশোধিত",
    status_due: "বকেয়া",

    // SIDEBAR NAVIGATION
    sidebar_dashboard: "ড্যাশবোর্ড",
    sidebar_buildings: "বিল্ডিং",
    sidebar_flats: "ফ্ল্যাট",
    sidebar_flat_owner: "ফ্ল্যাট মালিক",
    sidebar_tenants: "ভাড়াটে",
    sidebar_payment_status: "পেমেন্ট স্ট্যাটাস",
    sidebar_expenses: "খরচ",
    sidebar_account_payable: "পরিশোধযোগ্য হিসাব",
    sidebar_account_receivable: "প্রাপ্য হিসাব",
    sidebar_reports: "রিপোর্ট",
    sidebar_association: "অ্যাসোসিয়েশন",
    sidebar_settings: "সেটিংস",
    sidebar_logout: "লগ আউট",

    // BUILDINGS TAB
    buildings_title: "বিল্ডিং তথ্য",
    buildings_edit_btn: "বিল্ডিং তথ্য সম্পাদনা",
    buildings_name: "বিল্ডিংয়ের নাম",
    buildings_address: "ঠিকানা",
    buildings_floors: "মোট তলা",
    buildings_year: "নির্মাণ সাল",
    buildings_total_flats: "মোট ফ্ল্যাট",
    buildings_common: "সাধারণ এলাকা",
    buildings_occupied: "অধিকৃত ফ্ল্যাট",
    buildings_vacant: "খালি ফ্ল্যাট",
    buildings_fund_target: "মাসিক ফান্ড লক্ষ্যমাত্রা",
    buildings_fund_balance: "বিল্ডিং ফান্ড ব্যালেন্স",
    buildings_flat_details: "ফ্ল্যাটের বিবরণ",
    buildings_add_flat: "+ ফ্ল্যাট যোগ করুন",
    buildings_col_flat: "ফ্ল্যাট নং",
    buildings_col_floor: "তলা",
    buildings_col_size: "আকার (বর্গফুট)",
    buildings_col_charge: "সার্ভিস চার্জ",
    buildings_col_status: "অবস্থা",
    buildings_col_tenant: "বর্তমান ভাড়াটে",
    buildings_col_actions: "পদক্ষেপ",
    buildings_assign: "নিযুক্ত করুন",
    buildings_occupied_badge: "অধিকৃত",
    buildings_vacant_badge: "খালি",
    buildings_all_status: "সকল অবস্থা",

    // FLAT OWNER TAB
    flat_owner_title: "ফ্ল্যাট মালিক",
    flat_owner_add: "+ মালিক যোগ করুন",
    flat_owner_col_name: "মালিকের নাম",
    flat_owner_col_phone: "ফোন নম্বর",
    flat_owner_col_nid: "জাতীয় পরিচয়পত্র নম্বর",
    flat_owner_col_flat: "ফ্ল্যাট নং",
    flat_owner_col_since: "মালিকানা থেকে",
    flat_owner_col_tenant: "বসবাসকারী ভাড়াটে",
    flat_owner_col_status: "অবস্থা",
    flat_owner_col_actions: "পদক্ষেপ",
    flat_owner_active: "সক্রিয়",

    // TENANTS TAB
    tenants_title: "ভাড়াটে",
    tenants_add: "+ ভাড়াটে যোগ করুন",
    tenants_col_name: "নাম",
    tenants_col_phone: "ফোন নম্বর",
    tenants_col_nid: "জাতীয় পরিচয়পত্র নম্বর",
    tenants_col_flat: "ফ্ল্যাট নং",
    tenants_col_movein: "প্রবেশের তারিখ",
    tenants_col_charge: "মাসিক সার্ভিস চার্জ",
    tenants_col_status: "অবস্থা",
    tenants_col_actions: "পদক্ষেপ",
    tenants_active: "সক্রিয়",
    tenants_view: "দেখুন",
    tenants_total_paid: "এই বছর মোট পরিশোধ",
    tenants_advance: "অগ্রিম জমা",
    tenants_payment_history: "পেমেন্ট ইতিহাস",
    tenants_edit: "ভাড়াটে সম্পাদনা",
    tenants_remove: "ভাড়াটে সরান",

    // PAYMENT STATUS TAB
    payment_title: "পেমেন্ট স্ট্যাটাস",
    payment_add: "+ পেমেন্ট রেকর্ড করুন",
    payment_total_col: "মোট সংগ্রহযোগ্য",
    payment_collected_col: "মোট সংগৃহীত",
    payment_due_col: "মোট বকেয়া",
    payment_col_name: "বাসিন্দার নাম",
    payment_col_flat: "ফ্ল্যাট",
    payment_col_charge: "সার্ভিস চার্জ",
    payment_col_month: "মাস",
    payment_col_date: "পেমেন্টের তারিখ",
    payment_col_method: "পদ্ধতি",
    payment_col_status: "অবস্থা",
    payment_col_action: "পদক্ষেপ",
    payment_receipt: "রসিদ",
    payment_remind: "রিমাইন্ড",

    // EXPENSES TAB
    expenses_title: "খরচ",
    expenses_add: "+ খরচ যোগ করুন",
    expenses_total: "এই মাসের মোট খরচ",
    expenses_covered: "ফান্ড থেকে পরিশোধিত",
    expenses_borrowed: "পরিশোধযোগ্য (ধার করা)",
    expenses_col_date: "তারিখ",
    expenses_col_desc: "বিবরণ",
    expenses_col_amount: "পরিমাণ",
    expenses_col_category: "বিভাগ",
    expenses_col_paid_from: "কোথা থেকে পরিশোধিত",
    expenses_col_added_by: "যোগ করেছেন",
    expenses_fund: "ফান্ড",
    expenses_borrowed_badge: "ধার",
    expenses_all_categories: "সকল ক্যাটাগরি",
    expenses_total_label: "মোট খরচ",

    // ACCOUNT PAYABLE TAB
    ap_title: "পরিশোধযোগ্য হিসাব",
    ap_sub: "বিল্ডিং অ্যাসোসিয়েশন ফান্ড থেকে যে পরিমাণ ধার করেছে",
    ap_outstanding: "মোট বকেয়া পরিশোধযোগ্য",
    ap_add: "+ পরিশোধযোগ্য যোগ করুন",
    ap_col_desc: "খরচের বিবরণ",
    ap_col_date: "তারিখ",
    ap_col_amount: "ধার করা পরিমাণ",
    ap_col_pay_to: "কাকে পরিশোধ",
    ap_col_status: "অবস্থা",
    ap_col_action: "পদক্ষেপ",
    ap_unpaid: "অপরিশোধিত",
    ap_paid: "পরিশোধিত",
    ap_pending: "মুলতুবি",
    ap_mark_paid: "পরিশোধ হিসেবে চিহ্নিত",
    ap_done: "সম্পন্ন",
    ap_total_payable: "মোট পরিশোধযোগ্য",

    // ACCOUNT RECEIVABLE TAB
    ar_title: "প্রাপ্য হিসাব",
    ar_sub: "বাসিন্দাদের কাছ থেকে এখনও সংগ্রহ না হওয়া সার্ভিস চার্জ",
    ar_outstanding: "মোট বকেয়া প্রাপ্য",
    ar_add: "+ এন্ট্রি যোগ করুন",
    ar_collect_from: "সংগ্রহ করতে হবে",
    ar_residents: "জন বাসিন্দার কাছ থেকে",
    ar_col_name: "বাসিন্দার নাম",
    ar_col_flat: "ফ্ল্যাট",
    ar_col_type: "ধরন",
    ar_col_amount: "বকেয়া পরিমাণ",
    ar_col_due_date: "বকেয়ার তারিখ",
    ar_col_days: "বকেয়া দিন",
    ar_col_action: "পদক্ষেপ",
    ar_col_status: "অবস্থা",
    ar_send_reminder: "রিমাইন্ডার পাঠান",
    ar_remind: "রিমাইন্ড",
    ar_overdue: "বকেয়া",
    ar_upcoming: "আসন্ন",
    ar_total_receivable: "মোট প্রাপ্য",

    // REPORTS TAB
    reports_title: "রিপোর্ট",
    reports_sub: "আর্থিক সারসংক্ষেপ ও তথ্য",
    reports_generate: "ইনভয়েস তৈরি করুন",
    reports_download: "পিডিএফ ডাউনলোড",
    reports_print: "ইনভয়েস প্রিন্ট",
    reports_close: "বন্ধ করুন",
    reports_monthly_title: "মাসিক ইনভয়েস",
    reports_monthly_desc: "একটি নির্দিষ্ট ফ্ল্যাট/ভাড়াটের জন্য মাসিক সার্ভিস চার্জ ইনভয়েস তৈরি করুন",
    reports_full_title: "সম্পূর্ণ মাসিক রিপোর্ট ইনভয়েস",
    reports_full_desc: "পুরো অ্যাসোসিয়েশনের জন্য সম্পূর্ণ আর্থিক ইনভয়েস তৈরি করুন",
    reports_select_tenant: "ভাড়াটে বেছে নিন",
    reports_select_month: "মাস বেছে নিন",
    reports_select_year: "বছর",
    reports_generate_btn: "ইনভয়েস তৈরি করুন",
    reports_generate_full_btn: "সম্পূর্ণ ইনভয়েস তৈরি করুন",
    reports_generate_invoices: "ইনভয়েস তৈরি করুন",
    reports_monthly_collection: "মাসিক সংগ্রহ রিপোর্ট",
    reports_monthly_collection_desc: "মাস অনুযায়ী সার্ভিস চার্জ সংগ্রহের সারসংক্ষেপ",
    reports_expense_report: "খরচের রিপোর্ট",
    reports_expense_report_desc: "ক্যাটাগরি অনুযায়ী সকল খরচের বিস্তারিত বিবরণ",
    reports_outstanding_dues: "বকেয়া পেমেন্ট রিপোর্ট",
    reports_outstanding_dues_desc: "সকল মুলতুবি পেমেন্ট ও বকেয়ার তালিকা",
    reports_income_vs_expense: "আয় বনাম খরচ রিপোর্ট",
    reports_income_vs_expense_desc: "প্রতিটি বিল্ডিংয়ের লাভ/ক্ষতির সংক্ষিপ্ত বিবরণ",
    reports_generate_arrow: "তৈরি করুন →",
    reports_pdf_coming: "পিডিএফ ডাউনলোড শীঘ্রই আসছে",

    // ASSOCIATION TAB
    assoc_title: "অ্যাসোসিয়েশন",
    assoc_info_title: "অ্যাসোসিয়েশনের তথ্য",
    assoc_edit_btn: "অ্যাসোসিয়েশনের তথ্য সম্পাদনা",
    assoc_name: "অ্যাসোসিয়েশনের নাম",
    assoc_established: "প্রতিষ্ঠিত",
    assoc_total_members: "মোট সদস্য",
    assoc_admin: "অ্যাডমিন",
    assoc_roles_title: "ভূমিকা ও অনুমতি",
    assoc_add_role: "+ ভূমিকা যোগ করুন",
    assoc_col_role: "ভূমিকার নাম",
    assoc_col_permissions: "অনুমতি",
    assoc_col_members: "সদস্য সংখ্যা",
    assoc_col_actions: "পদক্ষেপ",
    assoc_edit_role: "সম্পাদনা",
    assoc_delete_role: "মুছুন",
    assoc_members_title: "অ্যাসোসিয়েশনের সদস্যরা",
    assoc_add_member: "+ সদস্য যোগ করুন",
    assoc_col_name: "নাম",
    assoc_col_phone: "ফোন",
    assoc_col_nid: "জাতীয় পরিচয়পত্র",
    assoc_col_joining: "যোগদানের তারিখ",
    assoc_col_status: "অবস্থা",
    assoc_remove: "সরান",
    assoc_note: "শুধুমাত্র অ্যাডমিন সদস্য যোগ/অপসারণ এবং ভূমিকা পরিচালনা করতে পারবেন।",
    assoc_save_role: "ভূমিকা সংরক্ষণ",
    assoc_add_member_btn: "সদস্য যোগ করুন",
    assoc_update_member_btn: "সদস্য আপডেট করুন",
    assoc_confirm_remove: "অ্যাসোসিয়েশন থেকে সরিয়ে দেবেন?",
    assoc_confirm_btn: "নিশ্চিত করুন",
    assoc_cancel_btn: "বাতিল",
    assoc_member_added: "সদস্য যোগ করা হয়েছে",
    assoc_member_removed: "সরানো হয়েছে",
    assoc_full_name: "পূর্ণ নাম",
    assoc_phone_number: "ফোন নম্বর",
    assoc_nid_number: "জাতীয় পরিচয়পত্র নম্বর",
    assoc_role: "ভূমিকা",
    assoc_joining_date: "যোগদানের তারিখ",

    // SETTINGS TAB
    settings_title: "সেটিংস",
    settings_building_title: "বিল্ডিং অ্যাসোসিয়েশন প্রোফাইল",
    settings_assoc_name: "অ্যাসোসিয়েশনের নাম",
    settings_address: "ঠিকানা",
    settings_floors: "মোট তলা",
    settings_total_flats: "মোট ফ্ল্যাট",
    settings_fund_target: "প্রতি ফ্ল্যাটের মাসিক ফান্ড লক্ষ্যমাত্রা",
    settings_save: "পরিবর্তন সংরক্ষণ",
    settings_notif_title: "বিজ্ঞপ্তির পছন্দ",
    settings_notif_1: "সার্ভিস চার্জ রিমাইন্ডার পাঠান (দেয় তারিখের ৩ দিন আগে)",
    settings_notif_2: "বাসিন্দাদের বকেয়া সতর্কবার্তা পাঠান",
    settings_notif_3: "পেমেন্ট নিশ্চিতকরণ রসিদ পাঠান",
    settings_notif_4: "ইমেইল বিজ্ঞপ্তি",
    settings_notif_5: "এসএমএস বিজ্ঞপ্তি",
    settings_account_title: "অ্যাকাউন্ট",
    settings_manager_name: "ম্যানেজারের নাম",
    settings_phone: "ফোন",
    settings_current_pass: "বর্তমান পাসওয়ার্ড",
    settings_new_pass: "নতুন পাসওয়ার্ড",
    settings_confirm_pass: "পাসওয়ার্ড নিশ্চিত করুন",
    settings_update: "প্রোফাইল আপডেট করুন",

    // PROPERTY MANAGEMENT SIDEBAR
    pm_sidebar_dashboard: "ড্যাশবোর্ড",
    pm_sidebar_properties: "আমার সম্পত্তি",
    pm_sidebar_units: "ইউনিট",
    pm_sidebar_tenants: "ভাড়াটে",
    pm_sidebar_rent: "ভাড়া পেমেন্ট",
    pm_sidebar_advance: "অগ্রিম অর্থের রেকর্ড",
    pm_sidebar_expenses: "খরচ",
    pm_sidebar_payable: "পরিশোধযোগ্য হিসাব",
    pm_sidebar_receivable: "প্রাপ্য হিসাব",
    pm_sidebar_settings: "সেটিংস",
    pm_property_management: "প্রপার্টি ম্যানেজমেন্ট",
    pm_overview: "আপনার সম্পত্তির সংক্ষিপ্ত বিবরণ",
    pm_my_properties: "আমার সম্পত্তি",
    pm_monthly_income: "মাসিক আয়",
    pm_active_tenants: "সক্রিয় ভাড়াটে",
    pm_pending_dues: "মুলতুবি বকেয়া",
    pm_across4: "৪টি অবস্থানে",
    pm_all_active: "সবাই সক্রিয়",
    pm_action_needed: "পদক্ষেপ প্রয়োজন",
    pm_income_trend: "আয় সংগ্রহের ট্রেন্ড",
    pm_manage_rentals: "আপনার ভাড়ার সম্পত্তি পরিচালনা করুন",
    pm_add_property: "সম্পত্তি যোগ করুন",
    pm_property_name: "সম্পত্তির নাম",
    pm_total_units: "মোট ইউনিট",
    pm_add_unit: "ইউনিট যোগ করুন",
    pm_all_units: "আপনার বিল্ডিংয়ের সকল ইউনিট",
    pm_all_tenants: "আপনার সকল ভাড়াটে",
    pm_all_rent_history: "সকল ভাড়া পেমেন্টের ইতিহাস",
    pm_record_payment: "পেমেন্ট রেকর্ড করুন",
    pm_track_transactions: "সকল ভাড়া লেনদেন ট্র্যাক করুন",
    pm_total_collectable: "মোট সংগ্রহযোগ্য",
    pm_rent_amount: "ভাড়ার পরিমাণ",
    pm_month: "মাস",
    pm_payment_date: "পেমেন্টের তারিখ",
    pm_advance_money: "অগ্রিম টাকার রেকর্ড",
    pm_advance_desc: "ভাড়াটেদের অগ্রিম পেমেন্ট ট্র্যাক করুন",
    pm_add_advance: "রেকর্ড যোগ করুন",
    pm_advance_amount: "অগ্রিম পরিমাণ",
    pm_date_received: "প্রাপ্তির তারিখ",
    pm_adjustment_status: "সমন্বয়ের অবস্থা",
    pm_notes: "মন্তব্য",
    pm_track_expenses: "বিল্ডিংয়ের খরচ ট্র্যাক করুন",
    pm_add_expense: "খরচ যোগ করুন",
    pm_property_profile: "সম্পত্তি প্রোফাইল",
    pm_this_month: "এই মাস",
    pm_unit: "ইউনিট",
    pm_property: "সম্পত্তি",
    pm_add_tenant: "ভাড়াটে যোগ করুন",
    pm_reminders: "রিমাইন্ডার",
    pm_reminders_desc: "রিমাইন্ডার ও বিজ্ঞপ্তি",
    pm_pending_reminders: "মুলতুবি রিমাইন্ডার",
    pm_days_overdue: "দিন বকেয়া",
    pm_send_reminder: "রিমাইন্ডার পাঠান",
    pm_sent_log: "প্রেরিত রিমাইন্ডার লগ",
    pm_date_sent: "প্রেরণের তারিখ",
    pm_type: "ধরন",
    pm_message: "বার্তা",
    pm_settings_desc: "আপনার ড্যাশবোর্ড সেটিংস পরিচালনা করুন",

    // GENERAL UI
    ui_search: "খুঁজুন",
    ui_filter: "ফিল্টার",
    ui_view: "দেখুন",
    ui_edit: "সম্পাদনা",
    ui_delete: "মুছুন",
    ui_save: "সংরক্ষণ",
    ui_cancel: "বাতিল",
    ui_close: "বন্ধ",
    ui_confirm: "নিশ্চিত",
    ui_loading: "লোড হচ্ছে...",
    ui_no_data: "এই মাসের জন্য কোনো তথ্য পাওয়া যায়নি।",
    ui_coming_soon: "এই বিভাগটি শীঘ্রই আসছে।",
    ui_days_overdue: "দিন বকেয়া",
    ui_all_buildings: "সকল বিল্ডিং",
    ui_all_status: "সকল অবস্থা",
    ui_occupied: "দখলকৃত",
    ui_vacant: "খালি",
    ui_paid: "পরিশোধিত",
    ui_due: "বকেয়া",
    ui_active: "সক্রিয়",
    ui_collected: "সংগৃহীত",
    ui_pending: "মুলতুবি",
    ui_total: "মোট",
    ui_actions: "পদক্ষেপ",
    ui_name: "নাম",
    ui_phone: "ফোন",
    ui_flat: "ফ্ল্যাট",
    ui_tenant: "ভাড়াটে",
    ui_amount: "পরিমাণ",
    ui_method: "পদ্ধতি",
    ui_status: "অবস্থা",
    ui_date: "তারিখ",
    ui_description: "বিবরণ",
    ui_category: "ক্যাটাগরি",
    ui_building: "বিল্ডিং",
    ui_size: "আকার",
    ui_rent: "ভাড়া",

    // Auth dashboard
    auth_dashboard: "ড্যাশবোর্ড",
    auth_my_profile: "আমার প্রোফাইল",
    auth_service_charge_updated: "সার্ভিস চার্জ আপডেট করা হয়েছে",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    try {
      const saved = localStorage.getItem("rento-language");
      if (saved === "en" || saved === "bn") return saved;
    } catch {}
    return "en";
  });

  useEffect(() => {
    localStorage.setItem("rento-language", lang);
    document.documentElement.style.fontFamily = lang === "bn"
      ? "'Hind Siliguri', 'Noto Sans Bengali', 'DM Sans', sans-serif"
      : "";
  }, [lang]);

  const setLang = (l: Lang) => setLangState(l);

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
